version: '3.3'
services:
  db:
    image: mysql:8
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: 'lumic'
      MYSQL_USER: 'lumic'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

  redis:
    image: redislabs/redisearch:latest
    restart: always
    ports:
      - '6345:6379'

volumes:
  my-db: