// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Image struct {
	ID       string         `json:"id"`
	Caption  string         `json:"caption"`
	UserName string         `json:"userName"`
	Link     string         `json:"link"`
	Slug     string         `json:"slug"`
	Created  string         `json:"created"`
	Category *ImageCategory `json:"category"`
}

type ImageCategory struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}

type NewImage struct {
	Link     string `json:"link"`
	Caption  string `json:"caption"`
	UserName string `json:"userName"`
	Category string `json:"category"`
}
